/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  HTTPError,
  HTTPError$inboundSchema,
  HTTPError$Outbound,
  HTTPError$outboundSchema,
} from "./httperror.js";
import {
  HTTPValidationError,
  HTTPValidationError$inboundSchema,
  HTTPValidationError$Outbound,
  HTTPValidationError$outboundSchema,
} from "./httpvalidationerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  StudioApiError,
  StudioApiError$inboundSchema,
  StudioApiError$Outbound,
  StudioApiError$outboundSchema,
} from "./studioapierror.js";

/**
 * Internal Server Error
 */
export type GenLLMGenerateResponse500ResponseBody = HTTPError | StudioApiError;

/**
 * Validation Error
 */
export type GenLLMGenerateResponseResponseBody =
  | HTTPValidationError
  | StudioApiError;

/**
 * Unauthorized
 */
export type GenLLMGenerateResponseBody = HTTPError | StudioApiError;

/**
 * Bad Request
 */
export type GenLLMResponseBody = HTTPError | StudioApiError;

/** @internal */
export const GenLLMGenerateResponse500ResponseBody$inboundSchema: z.ZodType<
  GenLLMGenerateResponse500ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([HTTPError$inboundSchema, StudioApiError$inboundSchema]);

/** @internal */
export type GenLLMGenerateResponse500ResponseBody$Outbound =
  | HTTPError$Outbound
  | StudioApiError$Outbound;

/** @internal */
export const GenLLMGenerateResponse500ResponseBody$outboundSchema: z.ZodType<
  GenLLMGenerateResponse500ResponseBody$Outbound,
  z.ZodTypeDef,
  GenLLMGenerateResponse500ResponseBody
> = z.union([HTTPError$outboundSchema, StudioApiError$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GenLLMGenerateResponse500ResponseBody$ {
  /** @deprecated use `GenLLMGenerateResponse500ResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    GenLLMGenerateResponse500ResponseBody$inboundSchema;
  /** @deprecated use `GenLLMGenerateResponse500ResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GenLLMGenerateResponse500ResponseBody$outboundSchema;
  /** @deprecated use `GenLLMGenerateResponse500ResponseBody$Outbound` instead. */
  export type Outbound = GenLLMGenerateResponse500ResponseBody$Outbound;
}

export function genLLMGenerateResponse500ResponseBodyToJSON(
  genLLMGenerateResponse500ResponseBody: GenLLMGenerateResponse500ResponseBody,
): string {
  return JSON.stringify(
    GenLLMGenerateResponse500ResponseBody$outboundSchema.parse(
      genLLMGenerateResponse500ResponseBody,
    ),
  );
}

export function genLLMGenerateResponse500ResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GenLLMGenerateResponse500ResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GenLLMGenerateResponse500ResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenLLMGenerateResponse500ResponseBody' from JSON`,
  );
}

/** @internal */
export const GenLLMGenerateResponseResponseBody$inboundSchema: z.ZodType<
  GenLLMGenerateResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([HTTPValidationError$inboundSchema, StudioApiError$inboundSchema]);

/** @internal */
export type GenLLMGenerateResponseResponseBody$Outbound =
  | HTTPValidationError$Outbound
  | StudioApiError$Outbound;

/** @internal */
export const GenLLMGenerateResponseResponseBody$outboundSchema: z.ZodType<
  GenLLMGenerateResponseResponseBody$Outbound,
  z.ZodTypeDef,
  GenLLMGenerateResponseResponseBody
> = z.union([
  HTTPValidationError$outboundSchema,
  StudioApiError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GenLLMGenerateResponseResponseBody$ {
  /** @deprecated use `GenLLMGenerateResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema = GenLLMGenerateResponseResponseBody$inboundSchema;
  /** @deprecated use `GenLLMGenerateResponseResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GenLLMGenerateResponseResponseBody$outboundSchema;
  /** @deprecated use `GenLLMGenerateResponseResponseBody$Outbound` instead. */
  export type Outbound = GenLLMGenerateResponseResponseBody$Outbound;
}

export function genLLMGenerateResponseResponseBodyToJSON(
  genLLMGenerateResponseResponseBody: GenLLMGenerateResponseResponseBody,
): string {
  return JSON.stringify(
    GenLLMGenerateResponseResponseBody$outboundSchema.parse(
      genLLMGenerateResponseResponseBody,
    ),
  );
}

export function genLLMGenerateResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GenLLMGenerateResponseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GenLLMGenerateResponseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenLLMGenerateResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const GenLLMGenerateResponseBody$inboundSchema: z.ZodType<
  GenLLMGenerateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([HTTPError$inboundSchema, StudioApiError$inboundSchema]);

/** @internal */
export type GenLLMGenerateResponseBody$Outbound =
  | HTTPError$Outbound
  | StudioApiError$Outbound;

/** @internal */
export const GenLLMGenerateResponseBody$outboundSchema: z.ZodType<
  GenLLMGenerateResponseBody$Outbound,
  z.ZodTypeDef,
  GenLLMGenerateResponseBody
> = z.union([HTTPError$outboundSchema, StudioApiError$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GenLLMGenerateResponseBody$ {
  /** @deprecated use `GenLLMGenerateResponseBody$inboundSchema` instead. */
  export const inboundSchema = GenLLMGenerateResponseBody$inboundSchema;
  /** @deprecated use `GenLLMGenerateResponseBody$outboundSchema` instead. */
  export const outboundSchema = GenLLMGenerateResponseBody$outboundSchema;
  /** @deprecated use `GenLLMGenerateResponseBody$Outbound` instead. */
  export type Outbound = GenLLMGenerateResponseBody$Outbound;
}

export function genLLMGenerateResponseBodyToJSON(
  genLLMGenerateResponseBody: GenLLMGenerateResponseBody,
): string {
  return JSON.stringify(
    GenLLMGenerateResponseBody$outboundSchema.parse(genLLMGenerateResponseBody),
  );
}

export function genLLMGenerateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GenLLMGenerateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenLLMGenerateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenLLMGenerateResponseBody' from JSON`,
  );
}

/** @internal */
export const GenLLMResponseBody$inboundSchema: z.ZodType<
  GenLLMResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([HTTPError$inboundSchema, StudioApiError$inboundSchema]);

/** @internal */
export type GenLLMResponseBody$Outbound =
  | HTTPError$Outbound
  | StudioApiError$Outbound;

/** @internal */
export const GenLLMResponseBody$outboundSchema: z.ZodType<
  GenLLMResponseBody$Outbound,
  z.ZodTypeDef,
  GenLLMResponseBody
> = z.union([HTTPError$outboundSchema, StudioApiError$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GenLLMResponseBody$ {
  /** @deprecated use `GenLLMResponseBody$inboundSchema` instead. */
  export const inboundSchema = GenLLMResponseBody$inboundSchema;
  /** @deprecated use `GenLLMResponseBody$outboundSchema` instead. */
  export const outboundSchema = GenLLMResponseBody$outboundSchema;
  /** @deprecated use `GenLLMResponseBody$Outbound` instead. */
  export type Outbound = GenLLMResponseBody$Outbound;
}

export function genLLMResponseBodyToJSON(
  genLLMResponseBody: GenLLMResponseBody,
): string {
  return JSON.stringify(
    GenLLMResponseBody$outboundSchema.parse(genLLMResponseBody),
  );
}

export function genLLMResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GenLLMResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenLLMResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenLLMResponseBody' from JSON`,
  );
}
