workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    livepeer-studio-api:
        inputs:
            - location: https://raw.githubusercontent.com/livepeer/studio/sk/schema-fixes/packages/api/src/schema/api-schema.yaml
targets:
    livepeer-ts:
        target: typescript
        source: livepeer-studio-api
        output: .
        codeSamples:
          output: codeSamples.yaml
