/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type CreateRoomResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success
     */
    createRoomResponse?: components.CreateRoomResponse | undefined;
    /**
     * Error
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export const CreateRoomResponse$inboundSchema: z.ZodType<
    CreateRoomResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
        "create-room-response": components.CreateRoomResponse$inboundSchema.optional(),
        error: errors.ErrorT$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
            "create-room-response": "createRoomResponse",
        });
    });

/** @internal */
export type CreateRoomResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
    "create-room-response"?: components.CreateRoomResponse$Outbound | undefined;
    error?: errors.ErrorT$Outbound | undefined;
};

/** @internal */
export const CreateRoomResponse$outboundSchema: z.ZodType<
    CreateRoomResponse$Outbound,
    z.ZodTypeDef,
    CreateRoomResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
        createRoomResponse: components.CreateRoomResponse$outboundSchema.optional(),
        error: errors.ErrorT$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
            createRoomResponse: "create-room-response",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateRoomResponse$ {
    /** @deprecated use `CreateRoomResponse$inboundSchema` instead. */
    export const inboundSchema = CreateRoomResponse$inboundSchema;
    /** @deprecated use `CreateRoomResponse$outboundSchema` instead. */
    export const outboundSchema = CreateRoomResponse$outboundSchema;
    /** @deprecated use `CreateRoomResponse$Outbound` instead. */
    export type Outbound = CreateRoomResponse$Outbound;
}
