/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../../models/components";
import { AxiosResponse } from "axios";

export class GetAllRequest extends SpeakeasyBase {
    /**
     * Filter the API response and retrieve a specific subset of stream objects based on certain criteria
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=streamsonly" })
    streamsonly?: string;
}

export class GetAllResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Success
     */
    @SpeakeasyMetadata({ elemType: components.Stream })
    classes?: components.Stream[];
}
