/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as errors from "../../models/errors";
import { z } from "zod";

export type GetAssetResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Success
     */
    assets?: Array<components.Asset> | undefined;
    /**
     * Error
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GetAssetResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        assets?: Array<components.Asset$.Inbound> | undefined;
        error?: errors.ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetAssetResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            assets: z.array(components.Asset$.inboundSchema).optional(),
            error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.assets === undefined ? null : { assets: v.assets }),
                ...(v.error === undefined ? null : { error: v.error }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        assets?: Array<components.Asset$.Outbound> | undefined;
        error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAssetResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            assets: z.array(components.Asset$.outboundSchema).optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.assets === undefined ? null : { assets: v.assets }),
                ...(v.error === undefined ? null : { error: v.error }),
            };
        });
}
