/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as errors from "../../models/errors";
import { z } from "zod";

export type GetMultistreamTargetResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Success
     */
    multistreamTargets?: Array<components.MultistreamTarget> | undefined;
    /**
     * Error
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GetMultistreamTargetResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        "multistream-targets"?: Array<components.MultistreamTarget$.Inbound> | undefined;
        error?: errors.ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetMultistreamTargetResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            "multistream-targets": z.array(components.MultistreamTarget$.inboundSchema).optional(),
            error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v["multistream-targets"] === undefined
                    ? null
                    : { multistreamTargets: v["multistream-targets"] }),
                ...(v.error === undefined ? null : { error: v.error }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        "multistream-targets"?: Array<components.MultistreamTarget$.Outbound> | undefined;
        error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetMultistreamTargetResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            multistreamTargets: z.array(components.MultistreamTarget$.outboundSchema).optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.multistreamTargets === undefined
                    ? null
                    : { "multistream-targets": v.multistreamTargets }),
                ...(v.error === undefined ? null : { error: v.error }),
            };
        });
}
