/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as errors from "../errors";
import * as z from "zod";

/**
 * Flag indicating if the response should only include recorded
 *
 * @remarks
 * sessions
 *
 */
export type RecordT = boolean | number;

export type GetRecordedSessionsRequest = {
    /**
     * ID of the parent stream
     */
    parentId: string;
    /**
     * Flag indicating if the response should only include recorded
     *
     * @remarks
     * sessions
     *
     */
    record?: boolean | number | undefined;
};

export type GetRecordedSessionsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success
     */
    data?: Array<components.Session> | undefined;
    /**
     * Error
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace RecordT$ {
    export const inboundSchema: z.ZodType<RecordT, z.ZodTypeDef, unknown> = z.union([
        z.boolean(),
        z.number().int(),
    ]);

    export type Outbound = boolean | number;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RecordT> = z.union([
        z.boolean(),
        z.number().int(),
    ]);
}

/** @internal */
export namespace GetRecordedSessionsRequest$ {
    export const inboundSchema: z.ZodType<GetRecordedSessionsRequest, z.ZodTypeDef, unknown> =
        z.object({
            parentId: z.string(),
            record: z.union([z.boolean(), z.number().int()]).optional(),
        });

    export type Outbound = {
        parentId: string;
        record?: boolean | number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRecordedSessionsRequest> =
        z.object({
            parentId: z.string(),
            record: z.union([z.boolean(), z.number().int()]).optional(),
        });
}

/** @internal */
export namespace GetRecordedSessionsResponse$ {
    export const inboundSchema: z.ZodType<GetRecordedSessionsResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            data: z.array(components.Session$.inboundSchema).optional(),
            error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        data?: Array<components.Session$.Outbound> | undefined;
        error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRecordedSessionsResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            data: z.array(components.Session$.outboundSchema).optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}
