/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type TerminateStreamRequest = {
  /**
   * ID of the stream
   */
  id: string;
};

export type TerminateStreamResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Error
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const TerminateStreamRequest$inboundSchema: z.ZodType<
  TerminateStreamRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type TerminateStreamRequest$Outbound = {
  id: string;
};

/** @internal */
export const TerminateStreamRequest$outboundSchema: z.ZodType<
  TerminateStreamRequest$Outbound,
  z.ZodTypeDef,
  TerminateStreamRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TerminateStreamRequest$ {
  /** @deprecated use `TerminateStreamRequest$inboundSchema` instead. */
  export const inboundSchema = TerminateStreamRequest$inboundSchema;
  /** @deprecated use `TerminateStreamRequest$outboundSchema` instead. */
  export const outboundSchema = TerminateStreamRequest$outboundSchema;
  /** @deprecated use `TerminateStreamRequest$Outbound` instead. */
  export type Outbound = TerminateStreamRequest$Outbound;
}

/** @internal */
export const TerminateStreamResponse$inboundSchema: z.ZodType<
  TerminateStreamResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type TerminateStreamResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const TerminateStreamResponse$outboundSchema: z.ZodType<
  TerminateStreamResponse$Outbound,
  z.ZodTypeDef,
  TerminateStreamResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TerminateStreamResponse$ {
  /** @deprecated use `TerminateStreamResponse$inboundSchema` instead. */
  export const inboundSchema = TerminateStreamResponse$inboundSchema;
  /** @deprecated use `TerminateStreamResponse$outboundSchema` instead. */
  export const outboundSchema = TerminateStreamResponse$outboundSchema;
  /** @deprecated use `TerminateStreamResponse$Outbound` instead. */
  export type Outbound = TerminateStreamResponse$Outbound;
}
