/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class CreateRoomResponse extends SpeakeasyBase {
    /**
     * The ID of the room
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
