/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { CreatorId, CreatorId$ } from "./creatorid";
import { z } from "zod";

export type InputCreatorId = CreatorId | string;

/** @internal */
export namespace InputCreatorId$ {
    export type Inbound = CreatorId$.Inbound | string;

    export type Outbound = CreatorId$.Outbound | string;

    export const inboundSchema: z.ZodType<InputCreatorId, z.ZodTypeDef, Inbound> = z.union([
        CreatorId$.inboundSchema,
        z.string(),
    ]);

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, InputCreatorId> = z.union([
        CreatorId$.outboundSchema,
        z.string(),
    ]);
}
