/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class IpfsExportParams extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "$ref" })
    dollarRef?: any;

    /**
     * Custom credentials for the Piñata service. Must have either
     *
     * @remarks
     * a JWT or an API key and an API secret.
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "pinata" })
    pinata?: any;
}
