/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { FfmpegProfile, FfmpegProfile$ } from "./ffmpegprofile";
import { InputCreatorId, InputCreatorId$ } from "./inputcreatorid";
import { Multistream, Multistream$ } from "./multistream";
import { PlaybackPolicy, PlaybackPolicy$ } from "./playbackpolicy";
import { z } from "zod";

export type NewStreamPayload = {
    name: string;
    creatorId?: InputCreatorId | undefined;
    /**
     * Whether the playback policy for a asset or stream is public or signed
     */
    playbackPolicy?: PlaybackPolicy | undefined;
    profiles?: Array<FfmpegProfile> | undefined;
    /**
     * Should this stream be recorded? Uses default settings. For more
     *
     * @remarks
     * customization, create and configure an object store.
     *
     */
    record?: boolean | undefined;
    multistream?: Multistream | undefined;
};

/** @internal */
export namespace NewStreamPayload$ {
    export type Inbound = {
        name: string;
        creatorId?: InputCreatorId$.Inbound | undefined;
        playbackPolicy?: PlaybackPolicy$.Inbound | undefined;
        profiles?: Array<FfmpegProfile$.Inbound> | undefined;
        record?: boolean | undefined;
        multistream?: Multistream$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<NewStreamPayload, z.ZodTypeDef, Inbound> = z
        .object({
            name: z.string(),
            creatorId: InputCreatorId$.inboundSchema.optional(),
            playbackPolicy: PlaybackPolicy$.inboundSchema.optional(),
            profiles: z.array(FfmpegProfile$.inboundSchema).optional(),
            record: z.boolean().optional(),
            multistream: Multistream$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                name: v.name,
                ...(v.creatorId === undefined ? null : { creatorId: v.creatorId }),
                ...(v.playbackPolicy === undefined ? null : { playbackPolicy: v.playbackPolicy }),
                ...(v.profiles === undefined ? null : { profiles: v.profiles }),
                ...(v.record === undefined ? null : { record: v.record }),
                ...(v.multistream === undefined ? null : { multistream: v.multistream }),
            };
        });

    export type Outbound = {
        name: string;
        creatorId?: InputCreatorId$.Outbound | undefined;
        playbackPolicy?: PlaybackPolicy$.Outbound | undefined;
        profiles?: Array<FfmpegProfile$.Outbound> | undefined;
        record?: boolean | undefined;
        multistream?: Multistream$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, NewStreamPayload> = z
        .object({
            name: z.string(),
            creatorId: InputCreatorId$.outboundSchema.optional(),
            playbackPolicy: PlaybackPolicy$.outboundSchema.optional(),
            profiles: z.array(FfmpegProfile$.outboundSchema).optional(),
            record: z.boolean().optional(),
            multistream: Multistream$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                name: v.name,
                ...(v.creatorId === undefined ? null : { creatorId: v.creatorId }),
                ...(v.playbackPolicy === undefined ? null : { playbackPolicy: v.playbackPolicy }),
                ...(v.profiles === undefined ? null : { profiles: v.profiles }),
                ...(v.record === undefined ? null : { record: v.record }),
                ...(v.multistream === undefined ? null : { multistream: v.multistream }),
            };
        });
}
