/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Approximate location of the pull source. The location is used to
 *
 * @remarks
 * determine the closest Livepeer region to pull the stream from.
 */
export type Location = {
    /**
     * Latitude of the pull source in degrees. North is positive,
     *
     * @remarks
     * south is negative.
     */
    lat: number;
    /**
     * Longitude of the pull source in degrees. East is positive,
     *
     * @remarks
     * west is negative.
     */
    lon: number;
};

/**
 * Configuration for a stream that should be actively pulled from an
 *
 * @remarks
 * external source, rather than pushed to Livepeer. If specified, the
 * stream will not have a streamKey.
 */
export type Pull = {
    /**
     * URL from which to pull from.
     */
    source: string;
    /**
     * Headers to be sent with the request to the pull source.
     */
    headers?: Record<string, string> | undefined;
    /**
     * Approximate location of the pull source. The location is used to
     *
     * @remarks
     * determine the closest Livepeer region to pull the stream from.
     */
    location?: Location | undefined;
};

/** @internal */
export namespace Location$ {
    export type Inbound = {
        lat: number;
        lon: number;
    };

    export const inboundSchema: z.ZodType<Location, z.ZodTypeDef, Inbound> = z
        .object({
            lat: z.number(),
            lon: z.number(),
        })
        .transform((v) => {
            return {
                lat: v.lat,
                lon: v.lon,
            };
        });

    export type Outbound = {
        lat: number;
        lon: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Location> = z
        .object({
            lat: z.number(),
            lon: z.number(),
        })
        .transform((v) => {
            return {
                lat: v.lat,
                lon: v.lon,
            };
        });
}

/** @internal */
export namespace Pull$ {
    export type Inbound = {
        source: string;
        headers?: Record<string, string> | undefined;
        location?: Location$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<Pull, z.ZodTypeDef, Inbound> = z
        .object({
            source: z.string(),
            headers: z.record(z.string()).optional(),
            location: z.lazy(() => Location$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                source: v.source,
                ...(v.headers === undefined ? null : { headers: v.headers }),
                ...(v.location === undefined ? null : { location: v.location }),
            };
        });

    export type Outbound = {
        source: string;
        headers?: Record<string, string> | undefined;
        location?: Location$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Pull> = z
        .object({
            source: z.string(),
            headers: z.record(z.string()).optional(),
            location: z.lazy(() => Location$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                source: v.source,
                ...(v.headers === undefined ? null : { headers: v.headers }),
                ...(v.location === undefined ? null : { location: v.location }),
            };
        });
}
