/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class RoomUserPayload extends SpeakeasyBase {
    /**
     * Display name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * Whether a user is allowed to publish audio/video tracks
     */
    @SpeakeasyMetadata()
    @Expose({ name: "canPublish" })
    canPublish?: boolean;

    /**
     * User defined payload to store for the participant
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: string;
}
