name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x]  # You can specify multiple Node.js versions to test against

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: failure()  # This will only run if previous steps fail
      with:
        name: test-results
        path: ./tests/reports/
        if-no-files-found: error # 'warn' or 'ignore' are also available, error will fail the step
